// Code generated by falafel 0.9.2. DO NOT EDIT.
// source: ./autopilot_api_generated.go

//go:build autopilotrpc
// +build autopilotrpc

package lndmobile

import (
	"context"
	"net"

	"github.com/golang/protobuf/proto"
	"google.golang.org/grpc"

	"github.com/lightningnetwork/lnd/lnrpc/autopilotrpc"
)

// setAutopilotDialOption sets the given method as the way
// to retrieve gprc options for the service.
func setAutopilotDialOption(f func() ([]grpc.DialOption, error)) {
	serviceDialOptionsMtx.Lock()
	defer serviceDialOptionsMtx.Unlock()

	serviceDialOptions["Autopilot"] = f
}

// applyAutopilotDialOptions returns extra grpc options to
// use when calling the service.
func applyAutopilotDialOptions() ([]grpc.DialOption, error) {
	serviceDialOptionsMtx.Lock()
	defer serviceDialOptionsMtx.Unlock()

	// First check the service options map, if there are any options
	// specific to this service.
	f, ok := serviceDialOptions["Autopilot"]
	if ok {
		return f()
	}

	// Otherwise return the default options.
	return defaultDialOptions()
}

// getAutopilotConn dials Autopilot with the current dial options,
// and returns the grpc client connection.
func getAutopilotConn() (*grpc.ClientConn, func(), error) {
	conn, err := lightningLis.Dial()
	if err != nil {
		return nil, nil, err
	}

	// Set up a custom dialer using the listener conn.
	dialer := func(context.Context, string) (net.Conn, error) {
		return conn, nil
	}

	// Create a dial options array.
	opts := []grpc.DialOption{
		grpc.WithContextDialer(dialer),
	}

	// Apply any extra server options.
	extraOpts, err := applyAutopilotDialOptions()
	if err != nil {
		return nil, nil, err
	}

	opts = append(opts, extraOpts...)

	// As address we use "localhost" to mimic a local connection.
	address := "localhost"
	clientConn, err := grpc.Dial(address, opts...)
	if err != nil {
		conn.Close()
		return nil, nil, err
	}

	closeConn := func() {
		conn.Close()
	}

	return clientConn, closeConn, nil
}

// getAutopilotClient returns a client connection to the server listening
// on lis.
func getAutopilotClient() (autopilotrpc.AutopilotClient, func(), error) {
	clientConn, closeConn, err := getAutopilotConn()
	if err != nil {
		return nil, nil, err
	}
	client := autopilotrpc.NewAutopilotClient(clientConn)
	return client, closeConn, nil
}

// Status returns whether the daemon's autopilot agent is active.
//
// NOTE: This method produces a single result or error, and the callback will
// be called only once.
func AutopilotStatus(msg []byte, callback Callback) {
	s := &syncHandler{
		newProto: func() proto.Message {
			return &autopilotrpc.StatusRequest{}
		},
		getSync: func(ctx context.Context,
			req proto.Message) (proto.Message, error) {

			// Get the gRPC client.
			client, closeClient, err := getAutopilotClient()
			if err != nil {
				return nil, err
			}
			defer closeClient()

			r := req.(*autopilotrpc.StatusRequest)
			return client.Status(ctx, r)
		},
	}
	s.start(msg, callback)
}

// ModifyStatus is used to modify the status of the autopilot agent, like
// enabling or disabling it.
//
// NOTE: This method produces a single result or error, and the callback will
// be called only once.
func AutopilotModifyStatus(msg []byte, callback Callback) {
	s := &syncHandler{
		newProto: func() proto.Message {
			return &autopilotrpc.ModifyStatusRequest{}
		},
		getSync: func(ctx context.Context,
			req proto.Message) (proto.Message, error) {

			// Get the gRPC client.
			client, closeClient, err := getAutopilotClient()
			if err != nil {
				return nil, err
			}
			defer closeClient()

			r := req.(*autopilotrpc.ModifyStatusRequest)
			return client.ModifyStatus(ctx, r)
		},
	}
	s.start(msg, callback)
}

// QueryScores queries all available autopilot heuristics, in addition to any
// active combination of these heruristics, for the scores they would give to
// the given nodes.
//
// NOTE: This method produces a single result or error, and the callback will
// be called only once.
func AutopilotQueryScores(msg []byte, callback Callback) {
	s := &syncHandler{
		newProto: func() proto.Message {
			return &autopilotrpc.QueryScoresRequest{}
		},
		getSync: func(ctx context.Context,
			req proto.Message) (proto.Message, error) {

			// Get the gRPC client.
			client, closeClient, err := getAutopilotClient()
			if err != nil {
				return nil, err
			}
			defer closeClient()

			r := req.(*autopilotrpc.QueryScoresRequest)
			return client.QueryScores(ctx, r)
		},
	}
	s.start(msg, callback)
}

// SetScores attempts to set the scores used by the running autopilot agent,
// if the external scoring heuristic is enabled.
//
// NOTE: This method produces a single result or error, and the callback will
// be called only once.
func AutopilotSetScores(msg []byte, callback Callback) {
	s := &syncHandler{
		newProto: func() proto.Message {
			return &autopilotrpc.SetScoresRequest{}
		},
		getSync: func(ctx context.Context,
			req proto.Message) (proto.Message, error) {

			// Get the gRPC client.
			client, closeClient, err := getAutopilotClient()
			if err != nil {
				return nil, err
			}
			defer closeClient()

			r := req.(*autopilotrpc.SetScoresRequest)
			return client.SetScores(ctx, r)
		},
	}
	s.start(msg, callback)
}
