// Code generated by falafel 0.9.2. DO NOT EDIT.
// source: ./peers_api_generated.go

//go:build peersrpc
// +build peersrpc

package lndmobile

import (
	"context"
	"net"

	"github.com/golang/protobuf/proto"
	"google.golang.org/grpc"

	"github.com/lightningnetwork/lnd/lnrpc/peersrpc"
)

// setPeersDialOption sets the given method as the way
// to retrieve gprc options for the service.
func setPeersDialOption(f func() ([]grpc.DialOption, error)) {
	serviceDialOptionsMtx.Lock()
	defer serviceDialOptionsMtx.Unlock()

	serviceDialOptions["Peers"] = f
}

// applyPeersDialOptions returns extra grpc options to
// use when calling the service.
func applyPeersDialOptions() ([]grpc.DialOption, error) {
	serviceDialOptionsMtx.Lock()
	defer serviceDialOptionsMtx.Unlock()

	// First check the service options map, if there are any options
	// specific to this service.
	f, ok := serviceDialOptions["Peers"]
	if ok {
		return f()
	}

	// Otherwise return the default options.
	return defaultDialOptions()
}

// getPeersConn dials Peers with the current dial options,
// and returns the grpc client connection.
func getPeersConn() (*grpc.ClientConn, func(), error) {
	conn, err := lightningLis.Dial()
	if err != nil {
		return nil, nil, err
	}

	// Set up a custom dialer using the listener conn.
	dialer := func(context.Context, string) (net.Conn, error) {
		return conn, nil
	}

	// Create a dial options array.
	opts := []grpc.DialOption{
		grpc.WithContextDialer(dialer),
	}

	// Apply any extra server options.
	extraOpts, err := applyPeersDialOptions()
	if err != nil {
		return nil, nil, err
	}

	opts = append(opts, extraOpts...)

	// As address we use "localhost" to mimic a local connection.
	address := "localhost"
	clientConn, err := grpc.Dial(address, opts...)
	if err != nil {
		conn.Close()
		return nil, nil, err
	}

	closeConn := func() {
		conn.Close()
	}

	return clientConn, closeConn, nil
}

// getPeersClient returns a client connection to the server listening
// on lis.
func getPeersClient() (peersrpc.PeersClient, func(), error) {
	clientConn, closeConn, err := getPeersConn()
	if err != nil {
		return nil, nil, err
	}
	client := peersrpc.NewPeersClient(clientConn)
	return client, closeConn, nil
}

// UpdateNodeAnnouncement allows the caller to update the node parameters
// and broadcasts a new version of the node announcement to its peers.
//
// NOTE: This method produces a single result or error, and the callback will
// be called only once.
func PeersUpdateNodeAnnouncement(msg []byte, callback Callback) {
	s := &syncHandler{
		newProto: func() proto.Message {
			return &peersrpc.NodeAnnouncementUpdateRequest{}
		},
		getSync: func(ctx context.Context,
			req proto.Message) (proto.Message, error) {

			// Get the gRPC client.
			client, closeClient, err := getPeersClient()
			if err != nil {
				return nil, err
			}
			defer closeClient()

			r := req.(*peersrpc.NodeAnnouncementUpdateRequest)
			return client.UpdateNodeAnnouncement(ctx, r)
		},
	}
	s.start(msg, callback)
}
