// Code generated by falafel 0.9.2. DO NOT EDIT.
// source: ./state_api_generated.go

package lndmobile

import (
	"context"
	"net"

	"github.com/golang/protobuf/proto"
	"google.golang.org/grpc"

	"github.com/lightningnetwork/lnd/lnrpc"
)

// setStateDialOption sets the given method as the way
// to retrieve gprc options for the service.
func setStateDialOption(f func() ([]grpc.DialOption, error)) {
	serviceDialOptionsMtx.Lock()
	defer serviceDialOptionsMtx.Unlock()

	serviceDialOptions["State"] = f
}

// applyStateDialOptions returns extra grpc options to
// use when calling the service.
func applyStateDialOptions() ([]grpc.DialOption, error) {
	serviceDialOptionsMtx.Lock()
	defer serviceDialOptionsMtx.Unlock()

	// First check the service options map, if there are any options
	// specific to this service.
	f, ok := serviceDialOptions["State"]
	if ok {
		return f()
	}

	// Otherwise return the default options.
	return defaultDialOptions()
}

// getStateConn dials State with the current dial options,
// and returns the grpc client connection.
func getStateConn() (*grpc.ClientConn, func(), error) {
	conn, err := lightningLis.Dial()
	if err != nil {
		return nil, nil, err
	}

	// Set up a custom dialer using the listener conn.
	dialer := func(context.Context, string) (net.Conn, error) {
		return conn, nil
	}

	// Create a dial options array.
	opts := []grpc.DialOption{
		grpc.WithContextDialer(dialer),
	}

	// Apply any extra server options.
	extraOpts, err := applyStateDialOptions()
	if err != nil {
		return nil, nil, err
	}

	opts = append(opts, extraOpts...)

	// As address we use "localhost" to mimic a local connection.
	address := "localhost"
	clientConn, err := grpc.Dial(address, opts...)
	if err != nil {
		conn.Close()
		return nil, nil, err
	}

	closeConn := func() {
		conn.Close()
	}

	return clientConn, closeConn, nil
}

// getStateClient returns a client connection to the server listening
// on lis.
func getStateClient() (lnrpc.StateClient, func(), error) {
	clientConn, closeConn, err := getStateConn()
	if err != nil {
		return nil, nil, err
	}
	client := lnrpc.NewStateClient(clientConn)
	return client, closeConn, nil
}

// NOTE: This method produces a stream of responses, and the receive stream can
// be called zero or more times. After EOF error is returned, no more responses
// will be produced.
func SubscribeState(msg []byte, rStream RecvStream) {
	s := &readStreamHandler{
		newProto: func() proto.Message {
			return &lnrpc.SubscribeStateRequest{}
		},
		recvStream: func(ctx context.Context,
			req proto.Message) (*receiver, func(), error) {

			// Get the gRPC client.
			client, closeClient, err := getStateClient()
			if err != nil {
				return nil, nil, err
			}

			r := req.(*lnrpc.SubscribeStateRequest)
			stream, err := client.SubscribeState(ctx, r)
			if err != nil {
				closeClient()
				return nil, nil, err
			}
			return &receiver{
				recv: func() (proto.Message, error) {
					return stream.Recv()
				},
			}, closeClient, nil
		},
	}
	s.start(msg, rStream)
}

// NOTE: This method produces a single result or error, and the callback will
// be called only once.
func GetState(msg []byte, callback Callback) {
	s := &syncHandler{
		newProto: func() proto.Message {
			return &lnrpc.GetStateRequest{}
		},
		getSync: func(ctx context.Context,
			req proto.Message) (proto.Message, error) {

			// Get the gRPC client.
			client, closeClient, err := getStateClient()
			if err != nil {
				return nil, err
			}
			defer closeClient()

			r := req.(*lnrpc.GetStateRequest)
			return client.GetState(ctx, r)
		},
	}
	s.start(msg, callback)
}
