// Code generated by falafel 0.9.2. DO NOT EDIT.
// source: ./versioner_api_generated.go

//go:build verrpc
// +build verrpc

package lndmobile

import (
	"context"
	"net"

	"github.com/golang/protobuf/proto"
	"google.golang.org/grpc"

	"github.com/lightningnetwork/lnd/lnrpc/verrpc"
)

// setVersionerDialOption sets the given method as the way
// to retrieve gprc options for the service.
func setVersionerDialOption(f func() ([]grpc.DialOption, error)) {
	serviceDialOptionsMtx.Lock()
	defer serviceDialOptionsMtx.Unlock()

	serviceDialOptions["Versioner"] = f
}

// applyVersionerDialOptions returns extra grpc options to
// use when calling the service.
func applyVersionerDialOptions() ([]grpc.DialOption, error) {
	serviceDialOptionsMtx.Lock()
	defer serviceDialOptionsMtx.Unlock()

	// First check the service options map, if there are any options
	// specific to this service.
	f, ok := serviceDialOptions["Versioner"]
	if ok {
		return f()
	}

	// Otherwise return the default options.
	return defaultDialOptions()
}

// getVersionerConn dials Versioner with the current dial options,
// and returns the grpc client connection.
func getVersionerConn() (*grpc.ClientConn, func(), error) {
	conn, err := lightningLis.Dial()
	if err != nil {
		return nil, nil, err
	}

	// Set up a custom dialer using the listener conn.
	dialer := func(context.Context, string) (net.Conn, error) {
		return conn, nil
	}

	// Create a dial options array.
	opts := []grpc.DialOption{
		grpc.WithContextDialer(dialer),
	}

	// Apply any extra server options.
	extraOpts, err := applyVersionerDialOptions()
	if err != nil {
		return nil, nil, err
	}

	opts = append(opts, extraOpts...)

	// As address we use "localhost" to mimic a local connection.
	address := "localhost"
	clientConn, err := grpc.Dial(address, opts...)
	if err != nil {
		conn.Close()
		return nil, nil, err
	}

	closeConn := func() {
		conn.Close()
	}

	return clientConn, closeConn, nil
}

// getVersionerClient returns a client connection to the server listening
// on lis.
func getVersionerClient() (verrpc.VersionerClient, func(), error) {
	clientConn, closeConn, err := getVersionerConn()
	if err != nil {
		return nil, nil, err
	}
	client := verrpc.NewVersionerClient(clientConn)
	return client, closeConn, nil
}

// GetVersion returns the current version and build information of the running
// daemon.
//
// NOTE: This method produces a single result or error, and the callback will
// be called only once.
func VersionerGetVersion(msg []byte, callback Callback) {
	s := &syncHandler{
		newProto: func() proto.Message {
			return &verrpc.VersionRequest{}
		},
		getSync: func(ctx context.Context,
			req proto.Message) (proto.Message, error) {

			// Get the gRPC client.
			client, closeClient, err := getVersionerClient()
			if err != nil {
				return nil, err
			}
			defer closeClient()

			r := req.(*verrpc.VersionRequest)
			return client.GetVersion(ctx, r)
		},
	}
	s.start(msg, callback)
}
